reviews:
  namespace: bookinfo-uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  image: ghcr.io/nattaphonmek/bookinfo-reviews
  tag: uat
ingress:
  host: uat.opsta.parfet.in.th
  path: "/reviews(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  ENABLE_RATINGS: true
  RATINGS_SERVICE: http://uat.opsta.parfet.in.th/ratings