def scmVars

pipeline {

  agent {
    kubernetes{
        yaml """
          apiVersion: v1
          kind: Pod
          spec:
						containers:
						- name: docker
							image: docker:20.10.3-dind
							command:
							- dockerd
							- --host=unix:///var/run/docker.sock
							- --host=tcp://0.0.0.0:2375
							- --storage-driver=overlay2
							ttv: true
              securityContext:
								priviledged: true
				""" 
    } // End kubernetes
  } // End agent

	stages{

		stage('Clone ratings source code'){
			steps{
				container('jnlp'){
					script{
						scmVars = git branch: 'dev',
													credentialId: 'deploy-key',
													url: ''
					}// End Script
				}// End Container
			}// End Step
		}// End Stage

		stage('Build Ratings Docker Image and push'){
			steps{
				container('docker'){
					script{
						docker.withRegistry('https://registry.demo.opsta.co.th','registry-bookinfo'){
							docker.build('registry.demo.opsta.co.th/ais/bookinfo/ratings:dev').push()
						}// End docker.withRegistry
					}// End script
				}// End container
			}// End steps
		}// End stage

	}// End Stages

} // End Pipeline